import Head from "next/head";
import { Button, ButtonGroup, useDisclosure } from "@chakra-ui/react";
// import {Button} from '@chakra-ui/react'
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
} from "@chakra-ui/react";

let username = "vicky.js@zestgeek.com";
let passs = "123456789";

export default function Home() {
  const [email, setEmail] = useState("");
  const [pass, setPass] = useState("");
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [changePass, setChangePass] = useState(false);
  const [newPass, setNewPass] = useState("");
  const [confirmPass, setConfirmPass] = useState("");

  const handleField = () => {
    if (email === username && pass === passs) {
      setChangePass(true);
    } else {
      alert("You are Not Signed");
    }
  };

  const handlePassword = () => {
    if (newPass != confirmPass) {
      alert("Password is not matching");
    } else {
      alert("password is matching");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="login-container">
          <div className="login-field">
            <div className="login-heading">
              <Image
                src="/images/logo.svg"
                width={122}
                height={100}
                alt="login-logo"
              />
              {changePass ? (
                <h1>Change Your Password</h1>
              ) : (
                <h1>Login to Your Account</h1>
              )}
            </div>
            {changePass ? (
              <div className="login-inputs">
                <input
                  type="password"
                  onChange={(e) => setNewPass(e.target.value)}
                  placeholder="Enter Your New Password"
                  value={newPass}
                />
                <input
                  onChange={(e) => setConfirmPass(e.target.value)}
                  value={confirmPass}
                  type="password"
                  placeholder="Confirm Your Password"
                />
                <Button
                  colorScheme="whatsapp"
                  onClick={() => {
                    handlePassword();
                  }}
                >
                  Login
                </Button>
              </div>
            ) : (
              <div className="login-inputs">
                <input
                  type="email"
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter Your Email"
                  value={email}
                />
                <input
                  onChange={(e) => setPass(e.target.value)}
                  value={pass}
                  type="password"
                  placeholder="******"
                />
                <Button
                  colorScheme="whatsapp"
                  onClick={(e) => {
                    handleField();
                  }}
                >
                  Login
                </Button>
              </div>
            )}

            {changePass ? (
              <Link href="/dashboard">
                {" "}
                <div className="skip-step">
                  <Button>Skip This step</Button>{" "}
                </div>
              </Link>
            ) : null}
          </div>
        </div>
        <div className="login_side-img"></div>
      </div>
    </>
  );
}
